stages:
  - lint
  - test

lint_backend:
  stage: lint
  script:
    - cd services/auth
    - npm i
    - npm run lint
  rules:
    - changes:
        - services/auth/**/*
    - if: '$CI_COMMIT_REF_NAME == "main"'

test_backend:
  stage: test
  script:
    - cd services/auth
    - npm i
    - npm test
  rules:
    - changes:
        - services/auth/**/*
    - if: '$CI_COMMIT_REF_NAME == "main"'
