version: "3.0"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./services/broker/data/:/var/lib/rabbitmq/
      - ./services/broker/log/:/var/log/rabbitmq

  authdb:
    image: postgres:11-alpine
    container_name: authdb
    volumes:
      - ./services/authdb/init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  pgbouncer:
    image: bitnami/pgbouncer:1.19.1-debian-11-r4
    container_name: pgbouncer
    ports:
      - "6432:6432"
    environment:
      POSTGRESQL_HOST: authdb
      POSTGRESQL_DATABASE: db_paranoid
      POSTGRESQL_USERNAME: paranoid
      POSTGRESQL_PASSWORD: development
      PGBOUNCER_DATABASE: db_paranoid
    depends_on:
      - authdb

  auth:
    container_name: auth
    build:
      context: ./services/auth
      dockerfile: ../../docker/auth.Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./services/auth:/home/node/app
      - ./shared:/home/node/app/shared
    restart: on-failure
    command: sh -c "npm run build && npx knex migrate:latest && npx knex seed:run && npm start"
    depends_on:
      - pgbouncer

  frontend:
    container_name: frontend
    build:
      context: ./services/frontend
      dockerfile: ../../docker/frontend.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./services/frontend:/home/node/app
    restart: on-failure
    command: npm start
