version: "3"

services:
  leaderboards:
    container_name: leaderboards
    build:
      context: ./services/leaderboards
      dockerfile: ../../docker/leaderboards.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./services/leaderboards:/home/node/app
    restart: on-failure
    command: npm start
