version: "3"

services:
  leaderboards:
    container_name: leaderboards
    build:
      context: ./services/leaderboards
      dockerfile: ../../docker/leaderboards.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./services/leaderboards:/home/node/app
    restart: on-failure
    command: npm start

  monitors:
    container_name: monitors
    build:
      context: ./services/monitors
      dockerfile: ../../docker/monitors.Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./services/monitors:/home/node/app
    restart: on-failure
    command: npm start

  proxy:
    container_name: proxy
    build:
      context: ./services/proxy
      dockerfile: ../../docker/proxy.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - leaderboards
      - monitors
