version: "3"

services:
  auth:
    container_name: auth
    build:
      context: ./services/auth
      dockerfile: ../../docker/auth.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./services/auth:/home/node/app
    restart: on-failure
    command: npm start
    depends_on:
      - pgbouncer

  auth.business:
    container_name: auth.business
    build:
      context: ./services/auth.business
      dockerfile: ../../docker/auth.business.Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./services/auth.business:/home/node/app
    restart: on-failure
    command: npm start

  proxy:
    container_name: proxy
    build:
      context: ./services/proxy
      dockerfile: ../../docker/proxy.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - auth
      - auth.business
